name: Git Config
description: Git config for redirects (e.g. mbed deploy requires)

inputs:
  github_token:
    description: "GitHub access token for accessing the private repos (required)."
    required: true

runs:
  using: composite
  steps:

    - name: Git config
      shell: bash
      run: |
          git config --global user.name "Izuma BOT"
          git config --global user.email "dmdevopsandsre@izumanetworks.com"
          git config --global url."https://${{ inputs.github_token }}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://${{ inputs.github_token }}@github".insteadOf "https://github"

